### PR TITLE
Fix protocol errors triggered by new clients after task state

### LINKED ISSUE #102: Handshake attempts after 'task' state trigger a protocol error
When a new responder connects, not only is the `new-responder` message being ignored, but also the responder that is trying to initiate a handshake triggers a protocol error because the initiator cannot find the responder in its map of responders.

Unfortunately, this implementation of the client has not been designed to fully reset its state to be able to do another handshake. The proposed solution is to drop the responder.

Furthermore, a `new-initiator` message also results in a protocol error after the handshake has been completed.

### LINKED ISSUE #103: Initiator should send drop-responder to the server, not the peer
This unfortunately leads to a protocol error if an initiator connects to a path with two lingering responders.

Oops. :joy:

### PR DESCRIPTION
**Pull request by lgrahl**
With this PR we handle `new-initiator` and `new-responder` after a peer handshake properly (somewhat). Resolves #102.

An initiator now simply drops new responders when it has already completed the handshake with another responder.

A responder now closes the connection when a new initiator connects after it has already completed a handshake with a previous initiator.

Note that this deviates from the intention of the specification to allow for more than one connection towards a responder over the same WebSocket connection. But resolving this would be far from trivial.

Also resolves #103.

### CODE REVIEW

File: src/main/java/org/saltyrtc/client/signaling/InitiatorSignaling.java [hunk 1]
```diff
@@ -503,12 +503,12 @@ private void sendAuth(Responder responder, SignalingChannelNonce nonce) throws S
     /**
      * Drop specific responder.
      */
-    private void dropResponder(Responder responder, @Nullable Integer reason) throws SignalingException, ConnectionException {
-        final DropResponder msg = new DropResponder(responder.getId(), reason);
-        final byte[] packet = this.buildPacket(msg, responder);
-        this.getLogger().debug("Sending drop-responder " + responder.getId());
+    private void dropResponder(final short responderId, @Nullable Integer reason) throws SignalingException, ConnectionException {
```
Comment (dbrgn) [inline src/main/java/org/saltyrtc/client/signaling/InitiatorSignaling.java]: Any reason to change the signature from `Responder` to `short`? While it works just as well, it reduces type safety because you could now accidentally swap responder id and reason code when calling the function.

Comment (lgrahl) [reply src/main/java/org/saltyrtc/client/signaling/InitiatorSignaling.java]: There's not always a `Responder` instance when dropping a responder. See `handleNewResponder`.

File: src/test/java/org/saltyrtc/client/tests/integration/ConnectionTest.java [hunk 2]
```diff
@@ -52,6 +53,68 @@
...
+            }
+
+            // Register state change event
+            peer.events.signalingStateChanged.register(event -> {
+                if (event.getState() == state) {
+                    done.countDown();
+                    return true;
+                }
+                return false;
+            });
```
[the remark this answers is not in the document]
Comment (lgrahl) [reply src/test/java/org/saltyrtc/client/tests/integration/ConnectionTest.java]: If that's being done from another thread, sure. But, since it's a test, let's not care until it happens.

File: src/main/java/org/saltyrtc/client/signaling/InitiatorSignaling.java (hunk 1 above)
Comment (dbrgn) [reply src/main/java/org/saltyrtc/client/signaling/InitiatorSignaling.java]: Ok, makes sense :slightly_smiling_face: I overlooked that.
